export enum ErrorTypeEnum {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNATHORIZED = 'AUTH_UNATHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_PASSWORDS_DO_NOT_MATCH = 'AUTH_PASSWORDS_DO_NOT_MATCH',

  TEAM_ALREADY_EXISTS = 'TEAM_ALREADY_EXISTS',
  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
  NO_PERMISSIONS = 'NO_PERMISSIONS',
  PLAYER_NOT_IN_A_TEAM = 'PLAYER_NOT_IN_A_TEAM',
  PLAYER_ALREADY_IN_THIS_TEAM = 'PLAYER_ALREADY_IN_THIS_TEAM',
  PLAYER_IN_ANOTHER_TEAM = 'PLAYER_IN_ANOTHER_TEAM',
  RELATION_NOT_FOUND = 'RELATION_NOT_FOUND',

  PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',
  TOURNAMENT_ALREADY_EXISTS = 'TOURNAMENT_ALREADY_EXISTS',
  PARTICIPANT_ALREADY_EXISTS = 'PARTICIPANT_ALREADY_EXISTS',

  APPLICATION_OF_WRONG_TYPE = 'APPLICATION_OF_WRONG_TYPE',
  STATS_NOT_FOUND = 'STATS_NOT_FOUND',
  STAT_ALREADY_EXISTS = 'STAT_ALREADY_EXISTS'
}